[project]
name = "heliodash"
version = "0.0.1"
requires-python = ">=3.10"

[build-system]
requires = ["setuptools >= 64"]
build-backend = "setuptools.build_meta"

[tool.ruff]
line-length = 79

[tool.ruff.lint]
extend-select = ["I"]